**PIVOT Tables com Pandas**

Uma PIVOT table serve para sumarizar características de um dataset maior

In [3]:
# Para exemplificar vamos utilizar o dataset das primarias americanas de 2016
import pandas as pd
import numpy as np

p_results_df = pd.read_csv('res/primary-results.csv')

In [5]:
# sumarizando informacoes sobre a soma dos votos por estado(state) partido(party) e candidatos(candidate)

pd.pivot_table(p_results_df,index=['state','party','candidate'],values=['votes'],aggfunc={'votes':np.sum}).head()

                                     votes
state   party      candidate
Alabama Democrat   Bernie Sanders    76399
                   Hillary Clinton  309928
        Republican Ben Carson        87517
                   Donald Trump     371735
                   John Kasich       37970

In [8]:
# Para deixar a sumarização mais interessante vamos inserir uma coluna de rank (por distrito e partido) no dataframe original
p_results_df['rank']=p_results_df.groupby(['county','party'])['votes'].rank(ascending=False)

#Verificando os dados para o distrito de Los Angeles
p_results_df[p_results_df['county'] == 'Los Angeles']

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes,rank
1385,California,CA,Los Angeles,6037.0,Democrat,Bernie Sanders,434656,0.420,2.0
1386,California,CA,Los Angeles,6037.0,Democrat,Hillary Clinton,590502,0.570,1.0
1519,California,CA,Los Angeles,6037.0,Republican,Donald Trump,179130,0.698,1.0
1520,California,CA,Los Angeles,6037.0,Republican,John Kasich,33559,0.131,2.0
1521,California,CA,Los Angeles,6037.0,Republican,Ted Cruz,30775,0.120,3.0

In [80]:
# sumarizando a o dataframe levando em conta a informacao do rank
pivot=pd.pivot_table(p_results_df,index=['state','county','party','candidate'],values=['votes','rank'],aggfunc={'votes':np.sum,'rank':np.min})

#contando o numero de vitorias que os candidatos de cada partido tiveram em cada distrito 
pivot[pivot['rank']==1.0].groupby(['candidate','party']).aggregate({'rank':np.sum})

                              rank
candidate       party
Ben Carson      Republican     1.0
Bernie Sanders  Democrat    1381.0
Donald Trump    Republican  1654.0
Hillary Clinton Democrat    1125.0
John Kasich     Republican    93.0
Marco Rubio     Republican    32.0
Ted Cruz        Republican   426.0