<br>**Agregação e agrupamento com PANDAS**

In [29]:
#importando csv com o resultado das primarias americanas de 2016


import pandas as pd
import numpy as np

presults=pd.read_csv('res/primary-results.csv')
print(presults.columns)
print(presults['votes'].mean())

Index(['state', 'state_abbreviation', 'county', 'fips', 'party', 'candidate',
       'votes', 'fraction_votes'],
      dtype='object')
2306.2527731502173

In [30]:
# agrupando  pela coluna candidate e usando agregadores para extrair o maximo o minimo e a media de votos
presults.groupby('candidate').aggregate({'votes':{min,np.mean,max}})

                       votes
                        mean min     max
candidate
 No Preference     23.225071   0     580
 Uncommitted        0.434343   0      16
Ben Carson        338.258238   0    9945
Bernie Sanders   2844.019501   0  434656
Carly Fiorina     139.366972   0    3612
Chris Christie    223.422018   1    7144
Donald Trump     3709.576408   0  179130
Hillary Clinton  3731.855410   0  590502
Jeb Bush          609.103226   2    9575
John Kasich      1160.052705   0  101217
Marco Rubio      1299.834051   0  111898
Martin O'Malley     7.595960   0     152
Mike Huckabee      33.787879   2     565
Rand Paul          85.646465   2    1633
Rick Santorum      18.000000   0     234
Ted Cruz         2120.191299   0  147721

In [31]:
# fazendo o mesmo para a fracao dos votos 
presults.groupby('candidate').aggregate({'fraction_votes':{min,np.mean,max}})

                fraction_votes
                          mean    min       max
candidate
 No Preference        0.006484  0.000  0.030000
 Uncommitted          0.000455  0.000  0.013000
Ben Carson            0.058941  0.000  0.415000
Bernie Sanders        0.493316  0.000  1.000000
Carly Fiorina         0.022097  0.000  0.117000
Chris Christie        0.017773  0.002  0.087195
Donald Trump          0.466217  0.000  0.915000
Hillary Clinton       0.461302  0.000  1.000000
Jeb Bush              0.044524  0.004  0.121000
John Kasich           0.122869  0.000  0.639000
Marco Rubio           0.146959  0.000  0.627000
Martin O'Malley       0.008303  0.000  0.132000
Mike Huckabee         0.024192  0.003  0.096000
Rand Paul             0.034061  0.006  0.096000
Rick Santorum         0.009960  0.000  0.073000
Ted Cruz              0.243453  0.000  1.000000

In [32]:
#verificando os distritos on hillary clinton teve 100 dos votos
presults[(presults['fraction_votes']==1) & (presults['candidate']=='Hillary Clinton')]

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
8142,Maine,ME,Amity,92300012.0,Democrat,Hillary Clinton,1,1.0
8160,Maine,ME,Atkinson,92300020.0,Democrat,Hillary Clinton,1,1.0
8168,Maine,ME,Avon,92300024.0,Democrat,Hillary Clinton,1,1.0
8186,Maine,ME,Beaver Cove,92300033.0,Democrat,Hillary Clinton,1,1.0
8188,Maine,ME,Beddington,92300034.0,Democrat,Hillary Clinton,1,1.0
8292,Maine,ME,Caswell,92300088.0,Democrat,Hillary Clinton,1,1.0
8334,Maine,ME,Crawford,92300111.0,Democrat,Hillary Clinton,1,1.0
8400,Maine,ME,Edinburg,92300144.0,Democrat,Hillary Clinton,1,1.0
8576,Maine,ME,Lakeville,92300235.0,Democrat,Hillary Clinton,1,1.0
8650,Maine,ME,Masardis,92300274.0,Democrat,Hillary Clinton,1,1.0
8700,Maine,ME,Moscow,92300301.0,Democrat,Hillary Clinton,1,1.0
8710,Maine,ME,New Canada,92300308.0,Democrat,Hillary Clinton,1,1.0
8744,Maine,ME,Northfield,92300322.0,Democrat,Hillary Clinton,1,1.0
8770,Maine,ME,Otis,92300338.0,Democrat,Hillary Clinton,1,1.0
8828,Maine,ME,Portage Lake,92300364.0,Democrat,Hillary Clinton,1,1.0
8866,Maine,ME,Roque Bluffs,92300384.0,Democrat,Hillary Clinton,1,1.0
8932,Maine,ME,Springfield,92300421.0,Democrat,Hillary Clinton,1,1.0
8974,Maine,ME,Sweden,92300438.0,Democrat,Hillary Clinton,1,1.0
9018,Maine,ME,Wade,92300464.0,Democrat,Hillary Clinton,1,1.0
9052,Maine,ME,Wellington,92300480.0,Democrat,Hillary Clinton,1,1.0
9070,Maine,ME,Westmanland,92300488.0,Democrat,Hillary Clinton,1,1.0
14088,Nebraska,NE,Hayes,31085.0,Democrat,Hillary Clinton,9,1.0
14174,Nebraska,NE,Thomas,31171.0,Democrat,Hillary Clinton,1,1.0

In [36]:
# criando uma  funcao de filtragem para aplicar no dataframe ela remove os cadidados com mais de 300000 votos
def minimum_votes_filter(x):
    #print(x['candidate'])
    #print("----> ",x['votes'].sum())
    #print(x['votes'])
    return x['votes'].sum() > 5500000
    
# apliucando a funcao no filter e agrupando os dados pela soma de votos de cada candidato
pd.DataFrame(presults.groupby('candidate').filter(minimum_votes_filter)).groupby('candidate').aggregate({'votes':{sum}})
#presults.groupby('candidate')['votes'].sum()

                    votes
                      sum
candidate
Bernie Sanders   11959102
Donald Trump     13302541
Hillary Clinton  15692452
Ted Cruz          7603006

In [34]:
# agrupando por mais de uma coluna para saber a votacao de cada canditado em cada estado
presults.groupby(['state','candidate'])['votes'].sum()

state    candidate
Alabama  Ben Carson          87517
         Bernie Sanders      76399
         Donald Trump       371735
         Hillary Clinton    309928
         John Kasich         37970
                             ...
Wyoming  Donald Trump           70
         Hillary Clinton       124
         John Kasich             0
         Marco Rubio           189
         Ted Cruz              644
Name: votes, Length: 290, dtype: int64